import Providers from "../../redux/Providers";
import "../../shared/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <div className="flex-1 bg-websiteBgColor">{children}</div>
      </Providers>
    </html>
  );
}
